name: e2e-workflow

on: 
  push:

jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build native with Maven
      run: mvn -B package
